##############################################################################
## Include module-specific Makefiles.  
##############################################################################
 include misc/subMakefile	# Miscellaneous support routines.
 include plat/subMakefile	# Platform-specific initialization
 include icart/subMakefile	# Intellicart emulation
 include util/subMakefile	# Utility programs
 include dasm/subMakefile	# Disassembler (dasm1600)


$(PROG): $(OBJS)

all: $(PROGS)
